# Generated by Django 2.0.3 on 2018-03-07 20:40

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rig_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('rig_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rig_name', models.CharField(default=None, max_length=50, null=True)),
                ('rig_email', models.CharField(default=None, max_length=50, null=True)),
                ('rig_lan_ip', models.CharField(default=None, max_length=50, null=True)),
                ('rig_claymore_version', models.CharField(default=None, max_length=4, null=True)),
                ('rig_time_up', models.CharField(default=None, max_length=10, null=True)),
                ('rig_reset_today', models.CharField(default=None, max_length=4, null=True)),
                ('rig_claymore_reset_today', models.CharField(default=None, max_length=10, null=True)),
                ('rig_gpu_info_eth', models.CharField(default=None, max_length=1000, null=True)),
                ('rig_gpu_second_coin', models.CharField(default=None, max_length=10, null=True)),
                ('rig_gpu_info_second_coin', models.CharField(default=None, max_length=1000, null=True)),
                ('rig_start_bat_data', models.CharField(default=None, max_length=1000, null=True)),
                ('location_uuid', models.CharField(default=None, max_length=50, null=True)),
                ('rig_reseter_number', models.IntegerField(default=None, null=True)),
                ('reset_uuid', models.CharField(default=None, max_length=1000, null=True)),
            ],
        ),
    ]
