# Generated by Django 2.0.3 on 2018-03-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rig', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rig',
            table='Rig',
        ),
    ]
