# Generated by Django 2.0.3 on 2018-03-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rig', '0002_auto_20180307_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rig',
            name='rig_uuid',
            field=models.UUIDField(),
        ),
    ]
