# Generated by Django 2.0.3 on 2018-03-19 13:30

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Rig', '0003_auto_20180309_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='rig',
            name='rig_last_connection',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, null=True),
        ),
    ]
