# Generated by Django 2.0.3 on 2018-03-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rig', '0004_rig_rig_last_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rig',
            name='rig_last_connection',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
