# Generated by Django 2.0.3 on 2018-03-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rig', '0005_auto_20180319_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rig',
            name='rig_last_connection',
            field=models.CharField(default='', max_length=50),
        ),
    ]
