# Generated by Django 2.0.3 on 2018-03-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rig', '0006_auto_20180319_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rig',
            name='rig_last_connection',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
