# Generated by Django 2.0.3 on 2018-03-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rig', '0008_auto_20180319_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rig',
            name='rig_last_connection',
            field=models.CharField(blank=True, default='1521486639.955969', max_length=50),
        ),
    ]
