# Generated by Django 2.0.3 on 2018-03-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rig', '0010_auto_20180319_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rig',
            name='rig_last_connection',
            field=models.CharField(default='1521487053.733575', max_length=50),
        ),
        migrations.AlterField(
            model_name='rig',
            name='rig_uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
