# Generated by Django 2.0.3 on 2018-03-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rig', '0011_auto_20180319_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rig',
            name='rig_last_connection',
            field=models.CharField(default='1521488380.186225', max_length=50),
        ),
    ]
