# Generated by Django 2.0.3 on 2018-03-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rig', '0013_auto_20180319_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rig',
            name='location_uuid',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rig',
            name='reset_uuid',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rig',
            name='rig_claymore_reset_today',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rig',
            name='rig_claymore_version',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='rig',
            name='rig_gpu_info_eth',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rig',
            name='rig_gpu_info_second_coin',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rig',
            name='rig_gpu_second_coin',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rig',
            name='rig_last_connection',
            field=models.CharField(default='1521495598.862337', max_length=50),
        ),
        migrations.AlterField(
            model_name='rig',
            name='rig_reset_today',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='rig',
            name='rig_reseter_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rig',
            name='rig_start_bat_data',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rig',
            name='rig_time_up',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
