# Generated by Django 2.0.3 on 2018-03-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rig', '0014_auto_20180319_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rig',
            name='rig_email',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rig',
            name='rig_gpu_info_eth',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rig',
            name='rig_gpu_info_second_coin',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rig',
            name='rig_last_connection',
            field=models.CharField(default='1521503779.002148', max_length=50),
        ),
        migrations.AlterField(
            model_name='rig',
            name='rig_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
