# Generated by Django 2.0.3 on 2018-03-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rig', '0015_auto_20180319_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='rig',
            name='rig_hashrate',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rig',
            name='rig_last_connection',
            field=models.CharField(default='1521593314.472329', max_length=50),
        ),
    ]
