# Generated by Django 2.0.3 on 2018-03-20 22:19

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Rig', '0016_auto_20180320_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rig',
            name='rig_gpu_info_eth',
            field=jsonfield.fields.JSONField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rig',
            name='rig_last_connection',
            field=models.CharField(default='1521598745.743752', max_length=50),
        ),
    ]
