# Generated by Django 2.0.3 on 2018-03-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rig', '0017_auto_20180320_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rig',
            name='rig_gpu_info_eth',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rig',
            name='rig_last_connection',
            field=models.CharField(default='1521599254.626393', max_length=50),
        ),
    ]
