# Generated by Django 2.0.3 on 2018-03-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eth_start_bat_data',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
