# Generated by Django 2.0.3 on 2018-03-07 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_eth_start_bat_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='eth_start_bat_data',
            new_name='start_bat_data',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='eth_wallet',
            new_name='wallet',
        ),
    ]
